version: "3"
services:
  mariadb:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=aslkjd1po3iasdklajkxjjxoox
      - MARIADB_DATABASE=mwl
      - MARIADB_USER=waristo
      - MARIADB_PASSWORD=1234
    container_name: mariadb
  pma:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    container_name: pma
#  spring:
#    image: waristo/mwl:latest
#    ports:
#      - 8080:8080
#    container_name: spring