logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
spring:
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        password: 1234
        url: jdbc:mariadb://localhost:3306/test
        username: wonbae
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
